services:
  n8n:
    image: n8nio/n8n
    container_name: n8n-app
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - ${N8N_DATA_FOLDER:-./data}:/home/node/.n8n
    environment:
      - DB_POSTGRESDB_PASSWORD=${DB_PASSWORD}
      - DB_POSTGRESDB_SCHEMA=public
      - DB_POSTGRESDB_USER=${DB_USER}
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_HOST=${DB_HOST}
      - DB_POSTGRESDB_DATABASE=${DB_NAME}
      - DB_TYPE=postgresdb
      - N8N_SECURE_COOKIE=false
    networks:
      external:
        ipv4_address: ${N8N_IP}

networks:
  external:
    external: true
    name: ${EXTERNAL_NETWORK_NAME}